name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install graphviz, plantuml and umlet
        run: |
          sudo apt-get -y install plantuml
          which plantuml
          sudo apt-get -y install graphviz
          set GRAPHVIZ_DOT=$(which dot)
          sudo apt-get -y install umlet
          which umlet
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: pipenv install --deploy --dev
      - name: Build package
        run: pipenv run python -m build
      - name: Create website
        run: pipenv run make html
      - name: Publish website
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/html
